# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader = "javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the FML version. This is currently 2.
loaderVersion = "${loader_version_range}" #mandatory

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license = "${mod_license}"

# A URL to refer people to when problems occur with this mod
issueTrackerURL = "https://github.com/kjmaster1/YieldNeoForge/issues"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId = "${mod_id}" #mandatory

# The version number of the mod
version = "${mod_version}" #mandatory

# A display name for the mod
displayName = "${mod_name}" #mandatory

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL = "https://github.com/kjmaster1/YieldNeoForge"

# A text field displayed in the mod UI
authors = "${mod_authors}" #optional

# The description text for the mod (multi line!) (#mandatory)
description = '''${mod_description}'''

displayTest = "IGNORE_ALL_VERSION"

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.${ mod_id }]] #optional
# the modid of the dependency
modId = "neoforge" #mandatory
# The type of the dependency. Can be one of "required", "optional", "incompatible" or "discouraged" (case insensitive).
# 'required' requires the mod to exist, 'optional' does not
# 'incompatible' will prevent the game from loading when the mod exists, and 'discouraged' will show a warning
type = "required" #mandatory
# Optional field describing why the dependency is required or why it is incompatible
# reason="..."
# The version range of the dependency
versionRange = "[${neo_version},)" #mandatory
# An ordering relationship for the dependency.
# BEFORE - This mod is loaded BEFORE the dependency
# AFTER - This mod is loaded AFTER the dependency
ordering = "NONE"
# Side this dependency is applied on - BOTH, CLIENT, or SERVER
side = "BOTH"

# Here's another dependency
[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "jei"
type = "optional"
versionRange = "[19.8.2.99,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${ mod_id }]]
modId = "curios"
type = "optional"
versionRange = "[9.5.1,)"
ordering = "AFTER"
side = "CLIENT"